### ISSUE TITLE
Gmx not working

### ISSUE THREAD

**Issue by kruku15** [stranac/x-notifier-scripts#1]
Hello,

the script for gmx.net does not work anymore

**Comment by zennube** [comment]
yes GMX not working. please help

**Comment by stranac** [comment]
I'll try fixing it as soon as I get some free time, I've been kinda overwhelmed with work stuff lately.

**Comment by zennube** [comment]
please help

**Comment by stranac** [comment]
Could someone provide a test account?
My old one is not working, and I can't make a new one since I don't have a German IP address.

I will probably have time to take a detailed look at the problem later today, or early next week if today doesn't work out for me.

**Comment by kruku15** [comment]
peter.michale@gmx.net/12345678

**Comment by zennube** [comment]
help help help please

**Comment by zennube** [comment]
nobody can help ?
